image: docker:git
services:
- docker:dind

stages:
- release
- deploy

variables:
  CONTAINER_TEST_IMAGE: gitlab.onlineterroir.com:5001/pitzzae/network-engine:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: gitlab.onlineterroir.com:5001/pitzzae/network-engine:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.onlineterroir.com:5001/pitzzae/network-engine

release-image:
  stage: release
  tags:
    - Atomos
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy-image:
  stage: deploy
  tags:
    - Shell
  script:
    - cd /nfs/docker/nginx-proxy/
    - docker-compose pull network-engine
    - docker-compose stop network-engine
    - sleep 5
    - docker-compose up -d network-engine
  only:
    - master
