image: docker:git
services:
- docker:dind

stages:
- release

variables:
  CONTAINER_TEST_IMAGE: gitlab.onlineterroir.com:5001/pitzzae/network-engine:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: gitlab.onlineterroir.com:5001/pitzzae/network-engine:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.onlineterroir.com:5001/pitzzae/network-engine

release-image:
  stage: release
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
